### ISSUE TITLE
使用时报错Read woff error

### ISSUE THREAD

**Issue by zhuba-Ahhh** [Lete114/rollup-plugin-font-minify#2]
未使用前是能正常打包的，可以帮忙看看嘛 仓库： https://github.com/zhuba-Ahhh/RichTextEditor
<img width="1297" alt="image" src="https://github.com/Lete114/rollup-plugin-font-minify/assets/84793349/5438fe3d-dd38-4f72-be6c-7dd1886e63f9">[plugin:rollup-font-minify] [plugin rollup-font-minify] [KaTeX_Caligraphic-Regular-Di6jR-x-.woff2] 6.91 kB ---> 5.28 kB
[plugin:rollup-font-minify] [plugin rollup-font-minify] [KaTeX_Caligraphic-Bold-Dq_IR9rO.woff2] 6.91 kB ---> 5.39 kB
[plugin:rollup-font-minify] [plugin rollup-font-minify] [KaTeX_Main-Bold-Cx986IdX.woff2] 25.32 kB ---> 14.98 kB
[plugin:rollup-font-minify] [plugin rollup-font-minify] [KaTeX_AMS-Regular-BQhdFMY1.woff2] 28.08 kB ---> 10.29 kB
[plugin:rollup-font-minify] [plugin rollup-font-minify] [KaTeX_Fraktur-Bold-CL6g_b3V.woff2] 11.35 kB ---> 9.11 kB
[plugin:rollup-font-minify] [plugin rollup-font-minify] [KaTeX_Fraktur-Regular-CTYiF6lA.woff2] 11.32 kB ---> 8.96 kB
[plugin:rollup-font-minify] [plugin rollup-font-minify] [KaTeX_Main-BoldItalic-DxDJ3AOS.woff2] 16.78 kB ---> 14.84 kB
[plugin:rollup-font-minify] [plugin rollup-font-minify] [KaTeX_Main-Italic-NWA7e6Wa.woff2] 16.99 kB ---> 14.86 kB
[plugin:rollup-font-minify] [plugin rollup-font-minify] [KaTeX_Main-Regular-B22Nviop.woff2] 26.27 kB ---> 16.34 kB
[plugin:rollup-font-minify] [plugin rollup-font-minify] [KaTeX_Math-BoldItalic-CZnvNsCZ.woff2] 16.40 kB ---> 14.37 kB
[plugin:rollup-font-minify] [plugin rollup-font-minify] [KaTeX_Math-Italic-t53AETM-.woff2] 16.44 kB ---> 14.36 kB
[plugin:rollup-font-minify] [plugin rollup-font-minify] [KaTeX_SansSerif-Bold-D1sUS0GD.woff2] 12.22 kB ---> 10.26 kB
[plugin:rollup-font-minify] [plugin rollup-font-minify] [KaTeX_Size1-Regular-mCD8mA8B.woff2] 5.47 kB ---> 1.96 kB
[plugin:rollup-font-minify] [plugin rollup-font-minify] [KaTeX_SansSerif-Italic-C3H0VqGB.woff2] 12.03 kB ---> 10.05 kB
[plugin:rollup-font-minify] [plugin rollup-font-minify] [KaTeX_Size2-Regular-Dy4dx90m.woff2] 5.21 kB ---> 1.94 kB
[plugin:rollup-font-minify] [plugin rollup-font-minify] [KaTeX_Size4-Regular-Dl5lxZxV.woff2] 4.93 kB ---> 2.02 kB
[plugin:rollup-font-minify] [plugin rollup-font-minify] [KaTeX_SansSerif-Regular-DDBCnlJ7.woff2] 10.34 kB ---> 8.56 kB
[plugin:rollup-font-minify] [plugin rollup-font-minify] [KaTeX_Script-Regular-D3wIWfF6.woff2] 9.64 kB ---> 7.95 kB
[plugin:rollup-font-minify] [plugin rollup-font-minify] [KaTeX_Typewriter-Regular-CO6r4hn1.woff2] 13.57 kB ---> 11.47 kB
x Build failed in 24.04s

✨ [vite-plugin-imagemin]- compressed image resource successfully: 
dist/icons/favicon.svg  -3%  1.49kb / tiny: 1.45kb

error during build:
Error: [rollup-font-minify] Read woff error
    at Object.raise (/Users/yanwenjun/My/workplace/RichTextEditor/node_modules/.pnpm/fonteditor-core@2.4.0/node_modules/fonteditor-core/lib/ttf/error.js:45:17)
    at woff2ttf (/Users/yanwenjun/My/workplace/RichTextEditor/node_modules/.pnpm/fonteditor-core@2.4.0/node_modules/fonteditor-core/lib/ttf/woff2ttf.js:58:27)
    at Font.read (/Users/yanwenjun/My/workplace/RichTextEditor/node_modules/.pnpm/fonteditor-core@2.4.0/node_modules/fonteditor-core/lib/ttf/font.js:116:43)
    at new Font (/Users/yanwenjun/My/workplace/RichTextEditor/node_modules/.pnpm/fonteditor-core@2.4.0/node_modules/fonteditor-core/lib/ttf/font.js:60:12)
    at Font.create (/Users/yanwenjun/My/workplace/RichTextEditor/node_modules/.pnpm/fonteditor-core@2.4.0/node_modules/fonteditor-core/lib/ttf/font.js:346:10)
    at minify (file:///Users/yanwenjun/My/workplace/RichTextEditor/node_modules/.pnpm/font-minify@0.0.0-alpha.2/node_modules/font-minify/dist/index.mjs:39:21)
    at Object.generateBundle (file:///Users/yanwenjun/My/workplace/RichTextEditor/node_modules/.pnpm/rollup-plugin-font-minify@0.0.0-alpha.0/node_modules/rollup-plugin-font-minify/src/index.js:77:32)
    at async Bundle.generate (file:///Users/yanwenjun/My/workplace/RichTextEditor/node_modules/.pnpm/rollup@4.17.2/node_modules/rollup/dist/es/shared/node-entry.js:18157:9)
    at async file:///Users/yanwenjun/My/workplace/RichTextEditor/node_modules/.pnpm/rollup@4.17.2/node_modules/rollup/dist/es/shared/node-entry.js:20696:27
    at async catchUnfinishedHookActions (file:///Users/yanwenjun/My/workplace/RichTextEditor/node_modules/.pnpm/rollup@4.17.2/node_modules/rollup/dist/es/shared/node-entry.js:20123:16)
 ELIFECYCLE  Command failed with exit code 1.

**Comment by lete114** [comment]
试了一下你仓库的代码，报错Read woff error是woff文件损坏导致的

你可以使用 https://font-minify.vercel.app/ 试一下你项目中的woff字体文件和网上随便下载一个woff字体文件

插件已更新，请更新到最新版
`pnpm add rollup-plugin-font-minify@latest -D`

**Comment by zhuba-Ahhh** [comment]
> 试了一下你仓库的代码，报错Read woff error是woff文件损坏导致的
> 
> 你可以使用 https://font-minify.vercel.app/ 试一下你项目中的woff字体文件和网上随便下载一个woff字体文件
> 
> 插件已更新，请更新到最新版 `pnpm add rollup-plugin-font-minify@latest -D`

好的，我试试，蟹蟹

**Comment by zhuba-Ahhh** [comment]
更新后打包成功
<img width="630" alt="image" src="https://github.com/Lete114/rollup-plugin-font-minify/assets/84793349/5b0064e9-3c3b-49f1-8831-1da5833deced">
